name: Build and publish images


on:
  push:
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        image: [cuda-ubuntu-base, ubuntu-base]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
  
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.image }}
          push: true
          tags: osbm/${{ matrix.image }}:latest
